news-feed/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'articles#index'
  resources :articles do
  	member do
      put "like", to: "articles#upvote"
    end
 end
end

news-feed/app/models/article.rb
class Article < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
end

news-feed/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	
 	has_many :articles
 	
end

news-feed/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

news-feed/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
  before_action :authenticate_user!, except: :index
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
      @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)
      doc = Nokogiri::HTML(open(@article.link))
      @article.title = doc.at_css("title").text
        respond_to do |format|
          if @article.save
            format.html { redirect_to @article, notice: 'Article was successfully created.' }
            format.json { render :show, status: :created, location: @article }
          else
            format.html { render :new }
            format.json { render json: @article.errors, status: :unprocessable_entity }
          end
        end
      end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @article.upvote_by current_user
    redirect_to :back
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :link, :user_id)
    end
    
    
    def correct_user
       @article = current_user.articles.find_by(id: params[:id])
       redirect_to articles_path, notice: "Not authorized to perform this action" if @article.nil?
    end

end

news-feed/app/helpers/application_helper.rb
module ApplicationHelper
end

news-feed/app/helpers/articles_helper.rb
module ArticlesHelper
end

news-feed/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

news-feed/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

news-feed/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>    
<div class="container">
    <% @articles.each do |article| %>
    <ul>
        <li><a href="<%= article.link %>" target="/"><h5><%= article.title %></h5></a></li>      
        <% if user_signed_in? && article.user_id == current_user.id %>
        <%= link_to 'Show', article %> |
        <%= link_to 'Edit', edit_article_path(article) %> |
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </li>
        <br/>
        <div class="btn-group">
         <%= link_to like_article_path(article), method: :put, class: "btn btn-default btn-sm" do %>
         <span class="glyphicon glyphicon-chevron-up"></span>
         Upvote
         <%= article.get_upvotes.size %>
         <% end %>
         </div>
        <hr class="divider"></p>
        </ul>
     <% end %> 
</div>
<br>

<%= will_paginate @posts %>

news-feed/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

news-feed/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @article.link %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

news-feed/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style type="text/css">
  .alert{
    color :red;
  }
</style>
<div class="container">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">News Forum</a>
    </div>
    <ul class="nav navbar-nav">
     <% if user_signed_in? %>
    <li><%= link_to 'New Article', new_article_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to 'Sign_Out', destroy_user_session_path, method: :delete %></li>
    <li><%= current_user.email %></li> 
      <% else %>
      <li><%= link_to 'Sign in', new_user_session_path %></a></li> |
      <li><%= link_to 'Register', new_user_registration_path %></a></li>
    </ul>
    <% end %>
  </div>
</nav>
  <p class="alert"><%= alert %>
  
</div>

<%= yield %>

</body>
</html>